public with sharing class adding {
    public static void adding() {
        Integer Amount1=100;
        Integer Amount2=600;
        Integer total=Amount1+Amount2;
        System.debug('my output is----'+total);

    }
    public static void sub(){
        Integer Amount1=100;
        Integer Amount2=700;
        Integer total=Amount1-Amount2;
        System.debug('my output is-----'+total);
}
}